# CTI110
# M6HW2 - Guessing Game
# Michael McKnight
# November 12, 2017

# This program has the user guess a number generated by the computer.

import random

def main():
    guessAttempts = 5
    correctNumber = random.randint(1, 100)

    for guess in range(guessAttempts):
        guess = int(input("I'm thinking of a number between 1 and 100. Guess: "))

        if guess < correctNumber:
            print("Too low, try again.")
        elif guess > correctNumber:
            print("Too high, try again.")
        else:
            print("You got it! You took", guessAttempts, "attempts.")

            break

    if guess != correctNumber:
        print("Whoops, you ran out of tries. The number was", correctNumber)

    while True:
        answer = input("Want to play again? (Y/N): ")
        if answer == "y":
            continue
        else:
            print("See you later.")
            exit()
        
main()
